server:
  port: 9001
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
  
  
spring:
  application:
    name: train-gateway
    
  cloud:
    gateway:
      routes:
      - id: Contact-Service
        uri: lb://Contact-Service
        predicates:
        - Path=/contacts/** 
      - id: Train-Service
        uri: lb://Train-Service
        predicates:
        - Path=/trains/**
      - id: Booking-Service
        uri: lb://Booking-Service
        predicates:
        - Path=/tickets/**
      - id: Profile-Service
        uri: http://localhost:8098
        predicates:
        - Path=/api/**
      - id: PAYTM-PAYMENT
        uri: lb://PAYTM-PAYMENT
        predicates:
        - Path=/**
 